#!/usr/bin/env bash
#
# SafeSpare AI — drive one full analysis of the synthetic demo statement
# against a running backend, so a judge lands on a populated dashboard
# instead of an empty-state screen.
#
#   ./infra/scripts/seed-demo.sh                          # deployed stack (URL from Terraform)
#   ./infra/scripts/seed-demo.sh http://localhost:8000    # local docker-compose stack
#
# The data is demo_data/demo_statement.csv, which is generated by
# scripts/generate_demo_statement.py and is labelled SYNTHETIC DEMO DATA on
# its first line. No real person's financial data is involved.
#
# Flow (spec §18 / §19):
#   POST /api/uploads/presign   -> presigned PUT URL + object key
#   PUT  <presigned url>        -> upload straight to the private S3 bucket
#   POST /api/analyses          -> start the pipeline
#   GET  /api/analyses/{id}/status  -> poll to COMPLETED
#   GET  /api/analyses/{id}/summary -> print the headline numbers
#
# NOTE (honesty flag): the backend API layer (backend/app/api/) was still
# empty when this script was written — it is written against the endpoint
# contract in spec §18, not against running code, and has never completed a
# real run. It fails loudly with the HTTP status and body when an endpoint is
# missing rather than pretending to have seeded anything.

set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_lib.sh"

require_cmd curl
require_cmd python3 "Needed to read JSON responses."

DEMO_CSV="${REPO_ROOT}/demo_data/demo_statement.csv"
[[ -f "${DEMO_CSV}" ]] \
  || die "${DEMO_CSV} not found. Generate it with: python3 scripts/generate_demo_statement.py"

######################################################################
# Resolve the API base URL
######################################################################

API_BASE="${1:-}"
if [[ -z "${API_BASE}" ]]; then
  require_cmd terraform
  API_BASE="$(tf_output backend_url)"
  log "Using deployed backend from Terraform: ${API_BASE}"
else
  log "Using backend: ${API_BASE}"
fi
API_BASE="${API_BASE%/}"

# jq is not assumed to be installed; python3 is already a hard dependency of
# the repo (scripts/generate_demo_statement.py), so use it as the JSON reader.
json_get() { # json_get <json> <dotted.path>
  python3 -c '
import json, sys
doc = json.loads(sys.argv[1] or "{}")
for part in sys.argv[2].split("."):
    if isinstance(doc, list):
        doc = doc[int(part)]
    else:
        doc = doc.get(part) if isinstance(doc, dict) else None
    if doc is None:
        break
print("" if doc is None else doc)
' "$1" "$2"
}

# api <METHOD> <path> [json-body] — fails loudly, printing the body, on non-2xx.
api() {
  local method="$1" path="$2" body="${3:-}" response status payload
  if [[ -n "${body}" ]]; then
    response="$(curl -sS -X "${method}" "${API_BASE}${path}" \
      -H 'Content-Type: application/json' \
      -d "${body}" \
      -w $'\n%{http_code}' --max-time 60)"
  else
    response="$(curl -sS -X "${method}" "${API_BASE}${path}" \
      -w $'\n%{http_code}' --max-time 60)"
  fi
  status="${response##*$'\n'}"
  payload="${response%$'\n'*}"
  if [[ "${status}" -lt 200 || "${status}" -ge 300 ]]; then
    warn "${method} ${path} -> HTTP ${status}"
    warn "${payload}"
    die "API call failed. If this is a 404, the endpoint is not implemented yet (backend/app/api/ was empty when this script was written)."
  fi
  printf '%s' "${payload}"
}

######################################################################
# 0. Health gate
######################################################################

log "Checking ${API_BASE}/health"
curl -fsS --max-time 15 "${API_BASE}/health" >/dev/null \
  || die "Backend is not healthy at ${API_BASE}/health. Nothing was seeded."
ok "Backend is up"

######################################################################
# 1. Presign
######################################################################

FILENAME="demo_statement.csv"
FILESIZE="$(wc -c < "${DEMO_CSV}" | tr -d ' ')"

log "Requesting a presigned upload URL"
PRESIGN="$(api POST /api/uploads/presign \
  "{\"filename\":\"${FILENAME}\",\"content_type\":\"text/csv\",\"size_bytes\":${FILESIZE}}")"

UPLOAD_URL="$(json_get "${PRESIGN}" upload_url)"
[[ -n "${UPLOAD_URL}" ]] || UPLOAD_URL="$(json_get "${PRESIGN}" url)"
OBJECT_KEY="$(json_get "${PRESIGN}" object_key)"
[[ -n "${OBJECT_KEY}" ]] || OBJECT_KEY="$(json_get "${PRESIGN}" key)"
UPLOAD_ID="$(json_get "${PRESIGN}" upload_id)"

[[ -n "${UPLOAD_URL}" ]] || die "No upload URL in the presign response: ${PRESIGN}"
# Deliberately not echoing UPLOAD_URL — a presigned URL is a bearer credential
# for the private uploads bucket and does not belong in a terminal scrollback
# or a CI log (§33 "presigned URL abuse").
ok "Received a presigned URL (not printed — it is a bearer credential)"
[[ -n "${OBJECT_KEY}" ]] && ok "Object key: ${OBJECT_KEY}"

######################################################################
# 2. Upload straight to S3
######################################################################

log "Uploading ${FILENAME} (${FILESIZE} bytes) directly to S3"
curl -fsS -X PUT "${UPLOAD_URL}" \
  -H 'Content-Type: text/csv' \
  --upload-file "${DEMO_CSV}" \
  --max-time 120 >/dev/null \
  || die "Presigned upload failed. The URL may have expired (default TTL is 15 minutes)."
ok "Uploaded"

######################################################################
# 3. Start the analysis
######################################################################

log "Creating the analysis"
BODY="{\"object_key\":\"${OBJECT_KEY}\",\"upload_id\":\"${UPLOAD_ID}\",\"filename\":\"${FILENAME}\",\"source\":\"demo-seed\"}"
ANALYSIS="$(api POST /api/analyses "${BODY}")"

ANALYSIS_ID="$(json_get "${ANALYSIS}" id)"
[[ -n "${ANALYSIS_ID}" ]] || ANALYSIS_ID="$(json_get "${ANALYSIS}" analysis_id)"
[[ -n "${ANALYSIS_ID}" ]] || die "No analysis id in the response: ${ANALYSIS}"
ok "Analysis ${ANALYSIS_ID} created"

######################################################################
# 4. Poll the state machine (§19)
######################################################################

log "Waiting for the pipeline to finish"
STATUS=""
for attempt in $(seq 1 60); do
  STATUS_DOC="$(api GET "/api/analyses/${ANALYSIS_ID}/status")"
  STATUS="$(json_get "${STATUS_DOC}" status)"
  [[ -n "${STATUS}" ]] || STATUS="$(json_get "${STATUS_DOC}" state)"
  printf '    [%02d/60] %s\n' "${attempt}" "${STATUS:-unknown}"

  case "${STATUS}" in
    COMPLETED)
      ok "Pipeline completed"
      break
      ;;
    FAILED)
      warn "${STATUS_DOC}"
      die "Analysis ${ANALYSIS_ID} reached FAILED."
      ;;
    AWAITING_REVIEW)
      # Extraction review is a human gate by design (§6.3, §8). Auto-confirming
      # it here is correct for a seed script and only for a seed script — the
      # UI must never skip it for a real user.
      log "AWAITING_REVIEW — auto-confirming the extracted rows for the demo"
      api POST /api/transactions/bulk-confirm \
        "{\"analysis_id\":\"${ANALYSIS_ID}\",\"confirm_all\":true}" >/dev/null
      ;;
  esac
  sleep 3
done

[[ "${STATUS}" == "COMPLETED" ]] \
  || die "Analysis ${ANALYSIS_ID} did not reach COMPLETED (last state: ${STATUS:-unknown})."

######################################################################
# 5. Print the headline numbers
######################################################################

log "Summary"
SUMMARY="$(api GET "/api/analyses/${ANALYSIS_ID}/summary")"
python3 -c '
import json, sys
try:
    doc = json.loads(sys.argv[1])
except json.JSONDecodeError:
    print(sys.argv[1]); raise SystemExit(0)
for k, v in doc.items():
    if isinstance(v, (dict, list)):
        v = f"<{type(v).__name__} of {len(v)}>"
    print(f"    {k}: {v}")
' "${SUMMARY}"

log "Safe Spare"
api GET "/api/analyses/${ANALYSIS_ID}/safe-spare" | python3 -c '
import json, sys
raw = sys.stdin.read()
try:
    doc = json.loads(raw)
except json.JSONDecodeError:
    print("    " + raw); raise SystemExit(0)
for k, v in doc.items():
    if isinstance(v, (dict, list)):
        v = f"<{type(v).__name__} of {len(v)}>"
    print(f"    {k}: {v}")
'

cat <<SUMMARY_TEXT

${C_BOLD}Demo seeded.${C_RESET}

  Analysis id   ${ANALYSIS_ID}
  API           ${API_BASE}
  Data          demo_data/demo_statement.csv (SYNTHETIC — not a real statement)

  Clean up when you are done:
    curl -X DELETE ${API_BASE}/api/analyses/${ANALYSIS_ID}

SUMMARY_TEXT
